org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=matlib
mod.name=MatLib
mod.group=net.mat0u5
mod.version=0.0.8
mod.version_prefix=
mod.version_suffix=
mod.authors=Mat0u5
mod.contributors=
mod.license=MIT
mod.description=A shared multi-platform minecraft library for my mods.
mod.sources_url=https://github.com/Mat0u5/MatLib
mod.homepage_url=https://github.com/Mat0u5/MatLib
mod.issues_url=https://github.com/Mat0u5/MatLib/issues
mod.discord_url=https://discord.gg/QWJxfb4zQZ

deps.minecraft=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.forge=[VERSIONED]

deps.lifeseries.min=1.5.9.7

# Publishing
publish.dryrun=false

publish.modrinth.id=gnefBeV1
publish.curseforge.id=1681583

publish.modrinth=true
publish.curseforge=true
publish.github=true
publish.discord=false

publish.release.fabric=alpha
publish.release.neoforge=alpha
publish.release.forge=alpha

publish.github.prerelease=false
publish.discord.dev=false

publish.github.branch=main
publish.github.target=Mat0u5/MatLib
